#!/bin/sh

# Quick start-stop-daemon example, derived from Debian /etc/init.d/ssh
set -e

# Must be a valid filename
NAME=wopr
PIDFILE=/var/run/wopr.pid
#This is the command to be run, give the full pathname
DAEMON_DIR="/home/miggles/rvanchat/current"
DAEMON="/usr/local/bin/bundle"
DAEMON_OPTS="exec rails runner lib/bot.rb -e production"
DAEMON_USER="www-data:www-data"

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
        echo -n "Starting daemon: "$NAME
  start-stop-daemon --start --quiet --background --pidfile $PIDFILE --chuid $DAEMON_USER --chdir $DAEMON_DIR --exec $DAEMON -- $DAEMON_OPTS
        echo "."
  ;;
  stop)
        echo -n "Stopping daemon: "$NAME
  start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE --chuid $DAEMON_USER
        echo "."
  ;;
  restart)
        echo -n "Restarting daemon: "$NAME
  start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile $PIDFILE --chuid $DAEMON_USER
  start-stop-daemon --start --quiet --background --pidfile $PIDFILE --chuid $DAEMON_USER --chdir $DAEMON_DIR --exec $DAEMON -- $DAEMON_OPTS
  echo "."
  ;;

  *)
  echo "Usage: "$1" {start|stop|restart}"
  exit 1
esac

exit 0
