# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 965821fe872700d7964a2bc44d5ceed0c54a09a92dfad5d1745377e756d7eb0f58b534540921f428c76d253c6ac50aea523549594becfbaaa9b35efe42586a31

test:
  secret_key_base: b6af4f1da1ad5c460c6178cd13485cb157d4bdb079b2d02dab64b864639cc277b84cbfb8479816e22a392c76675d04d97355fbfd5cab12cded79a51c0455087b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 22e4873e57c015bc84829abe106e5ff09b8a5a3e72b8cd33f329164122d161ebad01d5643e99ceb6c77e549a9544cab18513c8549006645d97b3143eedb96445
  # <%= ENV["SECRET_KEY_BASE"] %>
